spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  #配置自定义静态资源目录
  web:
    resources:
      static-locations:
        - classpath:/MEAT-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        - file:d:/temp/
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
mybatis:
  #配置mybatis映射文件
  mapper-locations: classpath:mapper/*.xml
  #配置mybatis的实体类别名
  type-aliases-package: com.tjetc.entity
  #mybatis的sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#设置日志输出级别
logging:
  level:
    com.tjetc: info
##  #设置日志文件的名称
#  file:
#    name: d:/log/MyLogUser.txt
server:
  port: 8081
netty:
  port: 8082
